language: rust

cache: cargo

rust:
  - 1.19.0
  - stable
  - beta
  - nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

script:
  - cargo fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email: false
